// Loader
export const HIDE_LOADER ="HIDE_LOADER";
export const SHOW_LOADER ="SHOW_LOADER";

// API calls
export const API ="API";
export const API_ERROR_RESPONSE ="API_ERROR_RESPONSE";
export const API_SAVE_RESPONSE ="API_SAVE_RESPONSE";

// search recipe
export const SEARCH_RECIPES ="SEARCH_RECIPES";
export const SEARCH_RECIPES_BY_INGREDIENTS ="SEARCH_RECIPES_BY_INGREDIENTS";
export const SAVE_RECIPES ="SAVE_RECIPES";
export const GET_RECIPES_DETAILS ="GET_RECIPES_DETAILS";
export const SAVE_RECIPES_DETAILS ="SAVE_RECIPES_DETAILS";

// set page no
export const SET_PAGE_NO = 'SET_PAGE_NO';