// Loader
export const HIDE_LOADER ="HIDE_LOADER";
export const SHOW_LOADER ="SHOW_LOADER";

// API calls
export const API ="API";
export const API_ERROR_RESPONSE ="API_ERROR_RESPONSE";
export const API_SAVE_RESPONSE ="API_SAVE_RESPONSE";

// UI Controls
export const SET_SEARCH_TEXT ="SET_SEARCH_TEXT";
export const SET_SEARCH_OPTION ="SET_SEARCH_OPTION";
export const SET_INGREDIENTS ="SET_INGREDIENTS";
export const DELETE_INGREDIENTS ="DELETE_INGREDIENTS";

// search recipe
export const SEARCH_RECIPES ="SEARCH_RECIPES";
export const SEARCH_RECIPES_BY_INGREDIENTS ="SEARCH_RECIPES_BY_INGREDIENTS";
export const SAVE_RECIPES ="SAVE_RECIPES";
export const GET_RECIPES_DETAILS ="GET_RECIPES_DETAILS";
export const SAVE_RECIPES_DETAILS ="SAVE_RECIPES_DETAILS";
export const RESET_RECIPES_DETAILS ="RESET_RECIPES_DETAILS";

// set page no
export const SET_PAGE_NO = 'SET_PAGE_NO';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';